
[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "npm run dev"
  framework = "vite"
  targetPort = 5173
  port = 8888
  publish = "dist"

[functions]
  external_node_modules = ["axios", "mongodb"]
